[theme]
base                    = "light"
primaryColor            = "#005CB4"   # dark Pepsi blue (“QUIK”)
secondaryBackgroundColor             = "#ADD8E6"   # sky blue (“PICK”)
textColor               = "#194481"   # navy text
font                    = "sans serif"