[theme]
primaryColor            = "#63A9DF"   # flip the two blues if you prefer
accentColor             = "#005CB4"
secondaryBackgroundColor = "#15233B"  # deep navy
backgroundColor         = "#000C1A"   # almost‑black
textColor               = "#E2ECF8"   # very‑pale sky blue